#!/usr/bin/python
##
# QEMU Object Model test tools
#
# Copyright IBM, Corp. 2011
#
# Authors:
#  Anthony Liguori   <aliguori@us.ibm.com>
#
# This work is licensed under the terms of the GNU GPL, version 2 or later.  See
# the COPYING file in the top-level directory.
##

import sys
from qmp import QEMUMonitorProtocol

srv = QEMUMonitorProtocol('/tmp/server.sock')
srv.connect()

path, prop = sys.argv[1].rsplit('.', 1)
print srv.command('qom-set', path=path, property=prop, value=sys.argv[2])
