#!/usr/bin/python
##
# Virtio Support
#
# Copyright IBM, Corp. 2011
#
# Authors:
#  Anthony Liguori   <aliguori@us.ibm.com>
#
# This work is licensed under the terms of the GNU GPL, version 2 or later.  See
# the COPYING file in the top-level directory.
##

import sys
from qmp import QEMUMonitorProtocol

srv = QEMUMonitorProtocol('/tmp/server.sock')
srv.connect()

if len(sys.argv) == 1:
    print '/'
    sys.exit(0)

for item in srv.command('qom-list', path=sys.argv[1]):
    if item['type'].startswith('child<'):
        print '%s/' % item['name']
    elif item['type'].startswith('link<'):
        print '@%s/' % item['name']
    else:
        print '%s' % item['name']
