#!/bin/sh
#
# Copyright IBM, Corp. 2012
#
# Authors:
#  Anthony Liguori <aliguori@us.ibm.com>
#
# This work is licensed under the terms of the GNU GPLv2 or later.
# See the COPYING file in the top-level directory.

cat <<EOF
<?xml version="1.0"?>
<gtester>
EOF

for file in "$@"; do
    first="yes"
    cat $file | while read LINE; do
	if test "$first" = "yes"; then
	    first="no"
	    continue
	fi
	if test "$LINE" = "<gtester>" -o "$LINE" = "</gtester>"; then
	    continue
	fi
	echo $LINE
    done
done

cat<<EOF
</gtester>
EOF
